XXXXXXXXX XXXXX
BBBB BBBBBB BBBBBBBBBB
XXXXX XXXXXXXXXX
XXXXXX
    XXXX XXXXXX XXX XXXXXXXX XXX
    XXXXXXXBBBBB BBBBB BBBBBBBB BBBBBXXXXXXXX
    XXXXX XXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
    XXXX XXXXXX XXX XXXXXXXX XXX
    XXXX XXXXXXXXXXXX XXX
    XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBXX
    XXXX XXXXXXXXXXXXXXXXXX XXX
    XXXXX XXXXXXXXX XXX
    XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBX XXXXXXXXXXXXXXX XXXXXXXXXXXX
    XXXXXX XXXXXXXXX XXX
    XXXX XXXXXXXXXXXXXXXXXX XXX
    XXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXX XXX
    XXXX XXXXXX XXX
    XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXXXXXXXXXXXXXXX
    XXXX XXXXXXX XXX
    BBBBBBBBBBBBBB
    BBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBB
XXXXXXX
XXXXXX
XXXX XXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXX

    XXXX XXXXXXXXXXXXXXXXXX XX BBBBB BBBBBB BBBBBBBB BBBBBBX XXXXXXXXX X
        BBBBBBB BBBBBBBBBBBBBBBBBBBBB
    XXXXXX
    XXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
        XXX XXXXXXXXXXXXXXXXXXXXXXXX
            XX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXX
        XXX XXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXX
    XXXXX
    BBBBB BBBBBBB

    BBBBBBBB BBBBBBB
    BBBBBBB BBBBBBBBBBBBBBBBBBBBB
XXXXXX
XXXXXXX
XXXXXXX