# Generated by Django 4.1.7 on 2023-03-04 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moves', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raiting',
            name='moves',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moves.moves', verbose_name='фильм'),
        ),
    ]
