XXXX XXXXXXXXXXXXX
	XXXXXXXX XXXXXXXXXX
XXXXXX

XXXX XXXXXXXXXXXXX
	XXXXXXXX XXXXXXXXXX
XXXXXX

XXXXXXXX
	XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

	XXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX X
		XXXXXXXXXXXXX XXXXXXXXXXX
	X X XX

	XXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX X
		XXXXXXXXXXXXXX XXXXXXXXXXXXXX
	X X XX
XXXXXXXXX
