BBBBBBB BBBBBBBBBBB
BBBBB BBBBBBB
XXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXX XXXXXXX
    BBBBB BBBBBBBBB
        XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
    BBBBBBBB BBBBBBBBB
        XXXX XXXXXXXXXXXX

            BBBBB BBBBBBB
            XXXX XXXXXXXXXXXXXXX XXXXXXXXXX
            BBBBBBBB BBBBBBB
            BBBBBBB BBBBBBBBBBBBBBBBBBBBBB
            XXXXXX
            BBBBB BBBBB
            BBBBBBBB BBBBB
        XXXXXX
    XXXXXX
XXXXXXXXXX
BBBBBBBB BBBBBBB