BBBBBBB BBBBBBBBBBBBBBBBBB
BBBBB BBBBBB XXX BBBBBBBB BBBBBB
BBBBB BBBBB
XXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX
    XXXX XXXXXXXXXXXX
        BBB BBBBB BB BBBBBBBBBB
        XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXXX
                    XXXX XXXXXX XXXXXXXXXXXXXXXXX XXXXXXX
                XXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXX XXXXXXXXX
                        XX XXXXXXX XXXXXXXXXXXXXXXXXXXX
                            
                        XXXX
                    XXXXX

                    XXXX XXXXXXXXXXXXXXXXXXXXXX
                        XXXX XXXXXXXXXXXXXXXXXXX
                            XXXXX XXXXXXXXXXXX XXXXXXXXXXXXX  XXXXXXX
                        XXXXXX
                    XXXXXX
                    XXX XXXXXXXXXXXXXX
                        XXXXXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXX
                        XXXXXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXX
                        XXXXXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXX
                XXXXXX
            XXXXXX
        XXXXXX
        BBBBBB
    XXXXXX
     XXXX XXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXX XX XXXX X
            BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBB
     XXXXXX
XXXXXX

BBBBBBBB BBBBB
XXXX XXXXXXXXX XXX

