BBBB BBBBBBBBB
BBBB BBBB BBBBBBBBB
XXXX XXXXXX XXX
XXXXXXX XXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
        XXXX XXX XXX
        XXXX XXXXXXXXXXXXX
            XXXX XXXXXXXXXX
                XXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                       XXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXX XXXXX XXXXXXX XXXXXXXX XXXXXX XXXXXXXX XXXX XXXXX XXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXX XXXXXXX XX XX XXX XXXXXXXXXXXX XXXXXXXXXXXX XXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXX
            XXXXXX

            XXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXX
            XXX XXXXXXXXXXX XXXXXX
                XXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXX
                    XXXX XXXXX XXXX XXXX XXXX XXX
                    XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXX XXXXXXXXXXXXXX
                                                                       XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX
                    XX XXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXX
                    XXXX
                        BBBBBBBBBBBBBB BB BBBBBBBBBB
                        BBB BBBBBBBB BB BBBBBBBBBB
                        XXXXXX XXXXXXXXXXXXXXXXXX
                        BBBBBB
                    XXXXX
                XXXXX
                XXXX
                    XXXXX XXXXXXXXBBB BBBBBBBBBBBBBBX XXXXXXXXXXXXXXBBBBBBBBBB
                        XXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXX
                        XXXXXXX XXXXXXXXXXXXXXXX
                            BBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBB
                            BBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBBBB
                            BBBBBBBBBBBBBBBBBBBBBB BBB BBBBBBBBB BB BBBBBBBBB
                            BBB BBBBBBBB BB BBBBBBBBB
                            XXXXXXX XXXXXXXX BB BBBBBBBBBBBBB BB BBBBBBBBBBBBB XXXXXXXXBBBBBX
                                 XX
                            XXXXXXXXX
                            BBBBBB
                        XXXXXXXXX
                        XXXXXX XXXXXXXXXXXXX XXXXXXXXXXX
                    XXXXXXX
                XXXXX
                XXXXXX XXXXXXXXXXXXXXXXXXX
                       XXXXXXXXXXXXX XXXXXXXX XXXX XXXXX XXXXXXXXXXXX XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                XXXXX
            XXXXX
        XXXXXX
        XXXX XXXXX XXX
    XXXXXX
XXXXXXXXX
XXXX XXXXXXXX XXX
XXXXXXXXXXXXXX
XXXX XXXXXXXXXXXXXXXXXXXX
    XX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXX XX XXXXXX XXXXX
    XXX XXXXXXXXXXX XXXXXXXXXXXXXXXX X XXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXX


    XXXXXX
XXXXXX
XXXXXX XXXXXXXXXXXX XXX
