XXX XXXXXXXXXXXXXXXXXXX
    BB BBBBBBBBBBBBBBBBBBBBB
        BB BBBBBBBBBBBBBBBBBBBBBBBB B B
            XXX XXXXXXXXXXXXXXXXXXXXXXXXX
                XX XXXXXXXXXXXXXXXXXXXX
            XXXXX
        BBBBB
        BB BBBBBBBBBBBBBBBBBBBBBBBB BB B
            XXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                    XX XXXXXXXXXXXXFFFFFFFFXX
                XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXX
                XXXX
            XXXXX
        BBBBB
    BBBBB
    BB BBBBBBBBBBBBBBBBBBBBBBBBBBB B B
        BBB B BB BBBBBBBBBBBBBBBBBBBB
            BB BBBBBBBBBBBBBBB BB B
                XXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX
                    XX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
                XXXXX
            BBBB B B BBBBBBBBBBBBBBBBBBBBBBBB BBB B B BBBBBBBBBBBBBBBBBBBBBBB
                XXX XXXXXXXXXXXXXXXXXXXXXXXXX
                        XX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
                XXXXX
            BBBBB
        BBBBBB
    BBBBB
    BB BBBBBBBBBBBBBBBBB
        BB BBBBBBBBBBBBBBBBBBBBBBB B BBBBBBBBBBBBBBBBBBBBBBBBBBBB
            XXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                    XX XXXXXXXXXXXXFFFFFFFXX
                XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXX
                XXXX
            XXXXX
        BBBBB
        BB BBBBBBBBBBBBBBBBBBBBBBB B BBBBBBBBBBBBBBBBBBBBBBBBBBBB
            XXX XXXXXXXXXXXXXXXXXXXXXXXXX
                    XX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
                        
                    XXXX
            XXXXX
        BBBBB
    BBBBB
XXXXX