BBBBBBB BBBBBBBBBBB
BBBBB BBBBBBB
    XXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXX XXXX XXXXXXXXXXXX
             XXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXX XXXXXXX
        XXXX XXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXX
                
            XXXXXX
        XXXXXX
    XXXXXXXXXX
BBBBBBBB BBBBBBB